// AUTO-GENERATED by typescript-type-def


/**
 * Payload data to be sent to newly created windows.
 * 
 * Each variant must correspond to the name of a Svelte component.
 */
export type Payload = (({
    "component": "FirstTimeSetup";
} & {
    "defaultConfigDir": string;
}) | {
    "component": "Query";
});

/**
 * Settings which can be changed by the end user.
 * 
 * Frontend code has direct access to this type so it should be kept simple in structure.
 */
export type Settings = {
};
